base:
    custom_metric: [R2, RMSE]
    random_state: 2024
    task_type: CPU
    devices: 0-3

optimize:
    n_estimators: trial.suggest_int("n_estimators", 50, 200),
    learning_rate: trial.suggest_float("learning_rate", 1e-3, 0.1, log=True),
    depth': trial.suggest_int("depth", 2, 16),
    l2_leaf_reg: trial.suggest_float("l2_leaf_reg", 0.1, 5),