base:
    model: lightgbm
    objective: regression
    metrics: [r2, mae, mse, rmse]
    verbosity: -1
    bagging_freq: 1
    device_type: gpu
    force_col_wise: true

    test_size: 0.000001
    validation_size: 0.2


optimize:
    n_trials: 100
    storage: "sqlite:///db.sqlite3"
    study_name: 2022_2023_lightgbm_all
    directions: [maximize, minimize, minimize, minimize]
    load_if_exists: true

    int: 
        n_estimators: 
            range: [100, 200]
        num_leaves: 
            range: [2, 1024]
        min_data_in_leaf: 
            range: [3, 100]
    float: 
        learning_rate: 
            range: [0.001, 0.2]
            args: {"log":true}
        subsample: 
            range: [0.05, 1.0]
        colsample_bytree: 
            range: [0.05, 1.0]
    

train:
    features: ['BlockP', 'BlockT', 'C1P', 'C1T', 'C1L', 'C2P', 'C2T',
        'C2interfacial_L', 'С2petrol_L', 'OH_T', 'OH_interfacial_L', 'OH_P',
        'C3T', 'C3L', 'P1Tinput', 'P1Toutput', 'P1Pinput', 'P1Poutput',
        'P1Тcoolant', 'P1Tgases', 'P1Рburner', 'P2Tinput', 'P2Toutput',
        'P2Pinput', 'P2Poutput', 'P2Tcoolant', 'P2Tgases', 'P2Pburner', 'Water']
    # без сепаратора и воды
    # features: ['BlockP', 'BlockT', 'C1P', 'C1T', 'C1L', 'P1Tinput',
    #     'P1Toutput', 'P1Pinput', 'P1Poutput', 'P1Тcoolant', 'P1Tgases',
    #     'P1Рburner', 'P2Tinput', 'P2Toutput', 'P2Pinput', 'P2Poutput',
    #     'P2Tcoolant', 'P2Tgases', 'P2Pburner']
    # c печкой-1
    # features: ['BlockP', 'BlockT', 'C1P', 'C1T', 'C1L', 'P1Tinput',
    #     'P1Toutput', 'P1Pinput', 'P1Poutput', 'P1Тcoolant', 'P1Tgases',
    #     'P1Рburner']
    # только блок и сепаратор-1
    # features: ['BlockP', 'BlockT', 'C1P', 'C1T', 'C1L']
    target: Vlagomer
    experiment_name: LightGBM_all_2022_2023
    train_name: LightGBM_2022_2023
    target_score: r2
    n_estimators: 1000


predict:
    pass


